[system]
tick_rate = 10 # how many times per second to tick

[telemetry]
socket = "/tmp/sub_tlm_socket"

[commanding]
socket = "/tmp/sub_cmd_socket"


# Hardware model configuration
[hardware.ballast.gpio]
intake_pin = 5
discharge_pin = 6

[hardware.debug.gpio]
debug_led_pin = 19

[hardware.dht11]
sample_interval = 10

[hardware.dht11.gpio]
data_pin = 12

[hardware.light.gpio]
light_pin = 21

[hardware.propulsion]
thrust_step_up = 0.05
thrust_step_down = 0.25

[hardware.propulsion.gpio]
aft_pin = 23
starboard_pin = 24
port_pin = 25
